### ISSUE TITLE
[프로그래머스] 코딩 테스트 게시글 삭제 요청

### ISSUE THREAD

**Issue by DemiHwang** [sewonkimm/sewonkimm.github.io#1]
안녕하세요. 프로그래머스의 운영자, Demi 입니다.

1주 전 메일로 연락을 드렸는데, 답변이 없어 다시 연락드립니다.

2919년 9월 작성하신 글에 저희 문제에 대한 내용이 있어 해당 게시글 삭제 요청 드립니다.
프로그래머스 잡페어 코딩테스트
https://sewonkimm.github.io/etc/2019/09/28/Programmers.html

프로그래머스의 문제는 모두 저작권의 보호를 받습니다. 
프로그래머스는 지문 및 테스트 케이스등 문제에 대한 정보를 복제, 공중송신, 배포하거나 2차 저작물을 작성하는 등의 행위를 제한하고 있습니다.
문제에 대한 정보를 당사의 동의 없이 타인에게 공개하거나 전달하는 행위는 당사의 재산을 침해하는 것으로, 
당사의 재산을 침해하는 이는 저작권법에 따라 5년 이하의 징역 또는 5천만 원 이하의 벌금에 처할 수 있습니다.

따라서 해당 게시글을 삭제해주시기 바랍니다.
금주 내로 게시글을 삭제/수정 하지 않을 시 다시 연락드리겠습니다.

감사합니다.
Demi 드림.

**Comment by sewonkimm** [comment]
삭제했습니다
